//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Cordinate")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Double")]
    pub x1: f64,
    #[sea_orm(column_type = "Double")]
    pub y1: f64,
    #[sea_orm(column_type = "Double")]
    pub x2: f64,
    #[sea_orm(column_type = "Double")]
    pub y2: f64,
    #[sea_orm(column_type = "Double")]
    pub width: f64,
    #[sea_orm(column_type = "Double")]
    pub height: f64,
    #[sea_orm(column_name = "pageNumber")]
    pub page_number: Option<i32>,
    #[sea_orm(column_name = "highlightedRectangleId")]
    pub highlighted_rectangle_id: Option<String>,
    #[sea_orm(column_name = "highlightedBoundingRectangleId")]
    pub highlighted_bounding_rectangle_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::highlight::Entity",
        from = "Column::HighlightedBoundingRectangleId",
        to = "super::highlight::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Highlight2,
    #[sea_orm(
        belongs_to = "super::highlight::Entity",
        from = "Column::HighlightedRectangleId",
        to = "super::highlight::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Highlight1,
}

impl ActiveModelBehavior for ActiveModel {}
