//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod account;
pub mod cordinate;
pub mod document;
pub mod feedback;
pub mod flashcard;
pub mod flashcard_attempt;
pub mod highlight;
pub mod message;
pub mod user;
