//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::account::Entity as Account;
pub use super::cordinate::Entity as Cordinate;
pub use super::document::Entity as Document;
pub use super::feedback::Entity as Feedback;
pub use super::flashcard::Entity as Flashcard;
pub use super::flashcard_attempt::Entity as FlashcardAttempt;
pub use super::highlight::Entity as Highlight;
pub use super::message::Entity as Message;
pub use super::user::Entity as User;
